//
// DtoAdapterTest.kt
// The Moshi codegen adapters against the section 4 wire contract. Runs as a
// plain JVM unit test; the adapters are generated by KSP at build time.
//

package com.burnpony.app

import com.burnpony.app.data.api.CreateNoteRequest
import com.burnpony.app.data.api.CreateNoteResponse
import com.burnpony.app.data.api.NoteStatusResponse
import com.squareup.moshi.Moshi
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

class DtoAdapterTest {

    private val moshi = Moshi.Builder().build()

    @Test
    fun createRequestUsesSnakeCaseWireNames() {
        val json = moshi.adapter(CreateNoteRequest::class.java).toJson(
            CreateNoteRequest(
                ciphertext = "{\"v\":1}",
                viewsAllowed = 3,
                expiresIn = 86_400,
                receiptEnabled = true,
            )
        )
        assertTrue(json.contains("\"views_allowed\":3"))
        assertTrue(json.contains("\"expires_in\":86400"))
        assertTrue(json.contains("\"receipt_enabled\":true"))
        assertTrue(json.contains("\"ciphertext\":"))
    }

    @Test
    fun parsesCreateResponse() {
        val response = moshi.adapter(CreateNoteResponse::class.java).fromJson(
            "{\"id\":\"AbCdEfGhIjKlMnOpQrStUv\"," +
                "\"management_token\":\"" + "a".repeat(64) + "\"," +
                "\"expires_at\":\"2026-07-11T18:00:00Z\"}"
        )!!
        assertEquals("AbCdEfGhIjKlMnOpQrStUv", response.id)
        assertEquals(64, response.managementToken.length)
        assertEquals("2026-07-11T18:00:00Z", response.expiresAt)
    }

    @Test
    fun parsesStatusResponseWithNullBurnedAtAndUnknownKeys() {
        val response = moshi.adapter(NoteStatusResponse::class.java).fromJson(
            "{\"views_allowed\":2,\"views_used\":1,\"receipt_enabled\":true," +
                "\"burned\":false,\"created_at\":\"2026-07-07T18:00:00Z\"," +
                "\"expires_at\":\"2026-07-14T18:00:00Z\",\"burned_at\":null," +
                "\"receipts\":[\"2026-07-08T09:30:00Z\"]," +
                "\"future_field\":123}"
        )!!
        assertEquals(2, response.viewsAllowed)
        assertEquals(1, response.viewsUsed)
        assertEquals(true, response.receiptEnabled)
        assertEquals(false, response.burned)
        assertNull(response.burnedAt)
        assertEquals(listOf("2026-07-08T09:30:00Z"), response.receipts)
    }
}
